services:
  traefik:
      image: docker.io/traefik:v3.2
      restart: unless-stopped
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./backend/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml

      networks:
        - bankfraud_local_nw
      command:
        - --providers.docker

  api: &api
    build:
      context: .
      dockerfile: ./backend/docker/local/fastapi/Dockerfile

    volumes:
      - .:/src 
      - ./backend/app/logs:/src/backend/app/logs
    ports:
      - "8000:8000"

    env_file:
      - ./.envs/.env.local

    
  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - bankfraud_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - bankfraud_local_nw

networks:
  bankfraud_local_nw:
    external: true

volumes:
  bankfraud_local_db:
